name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
inputs:
  caching-myname:
    description: 'Wheter to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  cache-used:
    description: 'Wheter the cache was used'
    value: ${{steps.install.outputs.cache-used}}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching-myname == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching-myname != 'true'
      run: |
        run npm ci
        echo "cache-used='${{inputs.aching-myname}}'" >> $GITHUB_OUTPUT
      shell: bash #extra setting when custom composite uses run key
      #composite action file has to have name action.yml, action.yaml, to be tomatically launched when pointing to folder
  